# Generated by Django 4.2.6 on 2023-11-22 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_books_alter_students_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 8, 57, 52, 823077)),
        ),
    ]
