# Generated by Django 4.2.6 on 2023-11-22 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_students_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 9, 27, 4, 348286)),
        ),
        migrations.AlterField(
            model_name='students',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
